### ISSUE TITLE
CCR import: Retrieving Providers

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#10]
Currently, a provider needs to be referenced within a nested `Source/Actor/ActorId` to be taken into account.
Then, in addition to the former reference, the Actor must have a mention of "care provider" within its `Source/Actor/ActorRole/Text` element.

Would it be possible to replace this or provide support for the premises that a provider is a provider, based on the fact that an NPI is present?
The XPath to get all providers (as Actor array) would then become: 

``` "//ccr:ContinuityOfCareRecord/ccr:Actors/ccr:Actor[ccr:IDs/ccr:Type/ccr:Text=\"NPI\"]"```
```

**Comment by ssayer** [comment]
Thanks for working the XPath out for me :). This issue is actually in health data standards, but I've updated that library to look for NPI instead of "care provider."

**Comment by kclaes** [comment]
Provider import works if all attributes are available.
However, the extract_data method in provider_import_utils.rb does not cope well with nil because it accesses content without checking the value of the at_xpath method.
Also, in provider_importer.rb, we have the following code:

``` ruby

          if actor.at_xpath('./ccr:Person/ccr:Name/ccr:CurrentName/ccr:Given')
            provider[:given_name] = actor.at_xpath('./ccr:Person/ccr:Name/ccr:CurrentName/ccr:Given').content
            provider[:family_name] = actor.at_xpath('./ccr:Person/ccr:Name/ccr:CurrentName/ccr:Family').content
          end
```

The nil-check is done for CurrentName/Given, but not for Family -> potential error?

If you fix the extract_data function to cope with nils, I guess it can just become

``` ruby
            provider[:given_name] = extract_data(actor, './ccr:Person/ccr:Name/ccr:CurrentName/ccr:Given')
            provider[:family_name] = extract_data(actor, './ccr:Person/ccr:Name/ccr:CurrentName/ccr:Family')
            provider[:specialty] = extract_data(actor, './ccr:Specialty/ccr:Text')
```

I changed the definition of extract_data to this

``` ruby
  # Returns nil if result is an empty string, block allows text munging of result if there is one
  def extract_data(subject, query)
    result = subject.at_xpath(query)
    if !result || result.content == ""
      nil
    else
      result
    end
  end
```

but perhaps there's a shorter ruby-way to do this ;)

**Comment by ssayer** [comment]
commited this to develop
