### ISSUE TITLE
Patient view not getting populated

### ISSUE THREAD

**Issue by addynaik** [pophealth/popHealth#106]
I used the initial patient data from the latest bundle to check the patient view and its not getting populated. 

http://cl.ly/image/3Z1h0G282D0H

the patient_results page shows up fine.. when i click the "patient_id" (which is actually the medical record number) it goes to the above page.. although I noticed the link is still using the [patient_id](https://github.com/pophealth/popHealth/blob/master/app/assets/javascripts/templates/patient_results/index.hbs#L15) 

If i change that to `medical_record_id` and `api/patients_controller.rb#load_patient` to `@patient = Record.by_patient_id(params[:id]).first` 

then the page works fine.. 

I pushed the changes here - https://github.com/port80labs/popHealth/commit/5e10ec14dac6a0619d93f705841d03b838efe4ea but havent added the tests yet as I dont fully understand the impact.

**Comment by eedrummer** [comment]
@port80labs We use the patient_id in the URL, so that is correct. We display the medical record number on the page, since that is what the user will be used to working with. I'm not sure why your patient view isn't getting populated. Would you be able to pass along any errors that might be showing up in the JavaScript console?

**Comment by sporkd** [comment]
I'm getting the same problem. One thing I noticed is that when hovering over the link to the patient, the id in the href does not match the id printed on the screen. Then when I click on the link, I get the following in the js console:

```
  GET http://localhost:3000/api/patients/5203afe2f7305cbf316eb5af?include_results=true 404 (Not Found)
```

Applying @port80labs changes fixed the issue, albeit with quite a lag before the patient is rendered.

**Comment by eedrummer** [comment]
@sporkd @port80labs I think I now understand what is going on here.

A little bit of history: The bundle that gets loaded by popHealth when you set it up was originally created by a sister project called [Cypress](http://projectcypress.org/). The bundle contains all of the information that Cypress needs to run. This includes not only the Meaningful Use clinical quality measures, but also the "test deck" of synthetic patients and a set of precomputed results for those patients. The last part seems to be where we are running into trouble.

The bundle import process is populating the records collection with synthetic patients. When it does that, it is assigning a new _id to each record it imports.

Where I think we are running into problems is that the importer is also populating the patient_cache collection. When it does this, it is putting in calculation results, which include a patient_id. Unfortunately, I believe that this patient_id is the one that was created in the application that created the bundle. This means when it is loaded into popHealth, it is pointing to a record that does not exist.

This would point to the problem being in the way we handle bundles and not the view code. To verify this, could you try running the unmodified code, but clean out your caches. You can do this by going into the Patients admin page and clicking the "Delete Caches" button, or you could go into MongoDB and drop the query_cache and patient_cache collections. After that, if you go back to the dashboard, the selected measures should recalculate and the patient views should work.

Would either of you be able to confirm this?

**Comment by addynaik** [comment]
I tried to do this but the data wasnt getting refreshed. I stopped the delayed_worker and ran the worker using rake.. I get this error. 

```
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] 2 jobs processed at 11.3484 j/s, 2 failed ...
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] 3 jobs processed at 9.1766 j/s, 3 failed ...
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 6 failed attempts
[Worker(host:pophealthinstance pid:4876)] 3 jobs processed at 8.7740 j/s, 3 failed ...
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] 2 jobs processed at 8.5776 j/s, 2 failed ...
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] 3 jobs processed at 7.9250 j/s, 3 failed ...
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 7 failed attempts
[Worker(host:pophealthinstance pid:4876)] 3 jobs processed at 9.0317 j/s, 3 failed ...
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 8 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 8 failed attempts
[Worker(host:pophealthinstance pid:4876)] 2 jobs processed at 7.6123 j/s, 2 failed ...
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 8 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 8 failed attempts
[Worker(host:pophealthinstance pid:4876)] QME::MapReduce::MeasureCalculationJob failed with RuntimeError: Expected one group from patient_cache aggregation, got 0 - 8 failed attempts
```

**Comment by sporkd** [comment]
Thanks @eedrummer. Dropping the collections manually in console and then reloading the page did work for me. But in the process of figuring out what was breaking I ended up creating the PR above to fix it on import.

**Comment by addynaik** [comment]
was able to do this as well.. cleared the cache and refreshed and it showed the information correctly..
