### ISSUE TITLE
CCR import: Retrieving Patient ID

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#11]
Currently, the patient ID is retrieved as the ActorId. 
This leads to problems when importing CCR's of different patients but with identical Actor ID's (which are merely references within the CCR).

Proposal to retrieve the ID from the IDs section as such:
`patient['medical_record_number'] = patientActor.at_xpath('./ccr:IDs/ccr:ID[../ccr:Type/ccr:Text="<systemname>"]').content`

Where `systemname` is a configurable identifier from pophealth.yml
When no `systemname` is defined, the first ID could be used:
`patient['medical_record_number'] = patientActor.at_xpath('./ccr:IDs/ccr:ID').content`
When no IDs are defined, as a last resort, the ActorID could be used.

**Comment by kclaes** [comment]
I've noticed that work has been started by making the patientId XPath a parameter in get_demographics, with ActorID being the default.
I was under the impression that it was decided to give preference to the values in the IDs section?

**Comment by ssayer** [comment]
Health Data Standards will used the Actor ID as the default. pophealth will pass in the XPath that uses the system name to identify a patient. I just pushed an update to the develop branch for this issue

**Comment by kclaes** [comment]
Works.

Changed our system name in pophealth.yml and the importer picked it up nicely.
