### ISSUE TITLE
upgrade ruby version

### ISSUE THREAD

**Issue by addynaik** [pophealth/popHealth#117]
the maintenance support for ruby 1.9.3 has lapsed on Feb 23rd 2014. The security updates will be provided until Feb 23rd 2015 but we should consider upgrading to ruby 2.1.1 or atleast 2.0.0

**Comment by eedrummer** [comment]
I think this is more a matter of changing the install instructions. Most of the team here at MITRE is running on Ruby 2.0.0. I know that we are testing on that in Travis-CI. It looks like you have tests working in 2.1, so I think that is a good target to move to.

**Comment by addynaik** [comment]
What about change to the ruby-version file in the repository? I'll create a pull request with update to travis config and submit it.

**Comment by Xodarap** [comment]
When I try to build pophealth v3.0.0, I get an error in `bundle install` because it's trying to use debugger which doesn't work in Ruby 2+. Has this really been removed? Is there something I have to change in my gemfile?

**Comment by eedrummer** [comment]
popHealth now uses Ruby 2.1.1. @Xodarap I think you were able to get this to work based on your mailing list comments. If not, please reopen.
