### ISSUE TITLE
OperationFailure in PatientsController#show

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#13]
When clicking on a patient in the measure details, the following error occurs:

---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---
Mongo::OperationFailure in PatientsController#show

Database command 'mapreduce' failed: {"assertion"=>"Invalid BSONObj size: 998050363 (0x3B0A7D3B) first element: : null", "assertionCode"=>10334, "errmsg"=>"db assertion failure", "ok"=>0.0}
Rails.root: C:/_work/pophealth/popHealth

Application Trace | Framework Trace | Full Trace
app/controllers/patients_controller.rb:38:in 'block in show'
app/controllers/patients_controller.rb:36:in 'show'
Request

Parameters:

{"id"=>"4f54b94da4f3d31cc4000004"}
Show session dump

_csrf_token: "46A5q6UNOFUK4SLqffeZsscMQrpA7G7VSNTmuyWSmAo="
session_id: "f7d916bb595db4043b1c5ac6e1487ce5"
warden.user.user.key: ["User", [BSON::ObjectId('4f4e2eb5a4f3d31f88000036')], "$2a$10$WP9SV8UHs9zL/f.52Nh0se"]
Show env dump

GATEWAY_INTERFACE: "CGI/1.1"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8"
HTTP_ACCEPT_CHARSET: "ISO-8859-1,utf-8;q=0.7,*;q=0.3"
HTTP_ACCEPT_ENCODING: "gzip,deflate,sdch"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.8"
REMOTE_ADDR: "127.0.0.1"
REMOTE_HOST: "localhost"
SERVER_NAME: "localhost"
SERVER_PROTOCOL: "HTTP/1.1"
Response

Headers:

None
---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---

**Comment by kclaes** [comment]
Any idea on this one guys? I've tried with both the develop and master branch as well as MongoDb 2.0.2 (latest one when I started trying Pophealth) and 2.0.4 (Currently the latest one)

**Comment by andrequina** [comment]
I should have some time to take a look at this tomorrow.

**Comment by andrequina** [comment]
This appears to be an issue related to MongoDB on windows.  I will double check to see if it is reproducible using the installer.

**Comment by pophealth** [comment]
Confirmed that this is an issue with memory size on windows.  We were able to reproduce under windows using mongo.  This is an issue with running mongo on a 32 bit architecture and only having 2GB of memory available.
