### ISSUE TITLE
CCR Import: Gender/Language/Race/Ethnicity

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#14]
Enhancement request to add Gender/Language/Race/Ethnicity to CCR import:
- Gender
  - Element: `/ContinuityOfCareRecord/Actors/Actor/Person/Gender`
  - CodeSystem: `./Code/CodeSystem` HL70001
  - Value: `./Code/Value` (M, F, ...)
  - Description: `./Text` (Male)
- Ethnicity
  - Element: `/ContinuityOfCareRecord/Body/SocialHistory/SocialHistoryElement[./Type/Text= "Ethnicity"]`
  - CodeSystem: `./Description/Code/CodingSystem` HL70189
  - Value: `./Description/Code/Value` (H, ...)
  - Description: `./Description/Text` (Hispanic, ...)
- Race
  - Element: `/ContinuityOfCareRecord/Body/SocialHistory/SocialHistoryElement[./Type/Text= "Race"]`
  - CodeSystem: `./Description/Code/CodingSystem` HL70005
  - Value: `./Description/Code/Value` (2028-9, ...)
  - Description: `./Description/Text` (Asian, ...)
- Language
  - Element: `/ContinuityOfCareRecord/Body/SocialHistory/SocialHistoryElement[./Type/Text= "Language"]`
  - CodeSystem: `./Description/Code/CodingSystem` ISO639-1
  - Value: `./Description/Code/Value` (en, ...)
  - Description: `./Description/Text` (English, ...)

**Comment by rdingwell** [comment]
Gender appeared to already be implemented. Race and Ethnicity have been implemented but are based off of the CDC race and ethnicity codes.  This code set was chosen as it is what is required for the C32 and we do not want to get into mapping between multiple code sets.

**Comment by kclaes** [comment]
Ethnicity and Race are parsed from the CCR, but don't get taken into account in the measures. I can select whatever I want for race/ethnicity, the measure will remain 0/0 unless I select none or all of the ethnicities/genders.
For Gender it works.

Language does not seem to be implemented yet?

**Comment by kclaes** [comment]
Example of imported record (I trimmed the measures object for conciseness)

```
{
  "_id" : ObjectId("4f699d86a4f3d31dd4000020"),
  "birthdate" : 602463600,
  "ethnicity" : {
    "code" : "2054-5"
  },
  "first" : "Francis",
  "gender" : "M",
  "languages" : null,
  "last" : "Theys",
  "measures" : {
  },
  "medical_record_number" : "0000002",
  "provider_performances" : [{
      "_id" : ObjectId("4f69dd67a4f3d31dbc000025"),
      "provider_id" : ObjectId("4f4e2ea3a4f3d31f88000032")
    }, {
      "_id" : ObjectId("4f69dd67a4f3d31dbc000026"),
      "provider_id" : ObjectId("4f4e2ea3a4f3d31f88000032")
    }],
  "race" : {
    "code" : "2135-2"
  }
}
```

Note: I manually tried adding code_set: 'CDC-RE' to the race/ethnicity hash, so it would be the same as the C32 importer, but this did not make a difference.

Note2: I cleaned all query caches before each attempt.

**Comment by ssayer** [comment]
After manually adding the code_set, did you clear BOTH the query cache and the patient cache?

**Comment by kclaes** [comment]
Yup -- at also seems that in code, the filter does not seem to care about the code_set?
(I cleared them with the new gui functionality and double checked in mongodb to see that both collections were empty)

**Comment by ssayer** [comment]
This issue should be fixed. The ethnicity and race codes were switched, which explains why you never found them when stratifying. Also we've updated the CCR importer to look for the string "CDC-RE" in the CCR instead of an OID.

**Comment by ssayer** [comment]
(I should add the fix is in health data standards NOT popHealth)
