### ISSUE TITLE
Period start date - confusing/wrong?

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#16]
The end-date gets passed as a parameter to the measure and that the start date is calculated in some measures in JavaScript. 
But what is the mention of the period start in the UI? Isn’t this confusing/wrong? Shouldn’t the measure itself determine which period it has to report over or at least have the date be a parameter to be passed to the measure calculation as well?
If it’s just a visual indication because NQF measures need to be reported quarterly, then perhaps something can be done to make this more clear? 
When defining custom measures, we’ll run into even more confusion with this seemingly useless field if those measure have an annual reporting period.

Suggestion/Question: possibility to pass starting date as parameter to measure and the possibility to enter this value (not being the hard coded 3 months)

**Comment by ssayer** [comment]
Will Not Fix
