### ISSUE TITLE
REST API for User/Provider

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#17]
Request to add REST API to manage Provider and User entities.
Basic CRUDS operations would be sufficient.

**Comment by ssayer** [comment]
Provider API was added with this commit https://github.com/pophealth/popHealth/commit/73dc3c4fdcf5ab21c506464251438ad6da93c11d. We do not have plans to add a USER CRUD API at this point due to possible security issues. I will put this in our "icebox" for future consideration.
