### ISSUE TITLE
Changes required for rails 4

### ISSUE THREAD

**Issue by rbclark** [pophealth/popHealth#171]
Since rails 4 has been released and mongoid 4 is about to be released, an experimental branch for this repository running rails 4 would be helpful for keeping the development in one place. I currently have a version of popHealth working on rails 4 with updated versions of QME and HDS, however I do not have a way to share it without a branch on this repository to push it to.

**Comment by eedrummer** [comment]
You can issue a pull request directly to master. Since popHealth 3.0.0 has been released, we are going to make the Rails 4/Mongoid 4 push.

**Comment by rbclark** [comment]
Got it, pull request is located at https://github.com/pophealth/popHealth/pull/173
