### ISSUE TITLE
Can't import the measure bundle

### ISSUE THREAD

**Issue by Pacane** [pophealth/popHealth#172]
I've downloaded the `bundle-latest.zip` file and tried to run the command to import the its content as stated in the docs:

`bundle exec rake bundle:import[/path/to/the/file/bundle-latest.zip,false,false,'*',true,true]`

however I get this error message: 

```
rake aborted!
Errno::ENOENT: No such file or directory - bundle.json
/home/joel/.rvm/gems/ruby-2.1.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:270:in `get_entry'
/home/joel/.rvm/gems/ruby-2.1.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:144:in `get_input_stream'
/home/joel/.rvm/gems/ruby-2.1.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:169:in `read'
/home/joel/.rvm/gems/ruby-2.1.1/gems/health-data-standards-3.4.6/lib/health-data-standards/import/bundle/importer.rb:93:in `unpack_bundle'
/home/joel/.rvm/gems/ruby-2.1.1/gems/health-data-standards-3.4.6/lib/health-data-standards/import/bundle/importer.rb:32:in `block in import'
/home/joel/.rvm/gems/ruby-2.1.1/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:90:in `open'
/home/joel/.rvm/gems/ruby-2.1.1/gems/health-data-standards-3.4.6/lib/health-data-standards/import/bundle/importer.rb:30:in `import'
/home/joel/.rvm/gems/ruby-2.1.1/gems/health-data-standards-3.4.6/lib/health-data-standards/tasks/bundle.rake:43:in `block (2 levels) in <top (required)>'
/home/joel/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/joel/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => bundle:import
(See full trace by running task with --trace)
```

The zip file contains bundle.json though... Is there anything special not mentioned in the doc, that would be supposed to help for this?

**Comment by rdingwell** [comment]
can you post the bundle either here in the issue or on the pophealth talk list?  I think the cypress server that hosts the bundles is having issues (as it is currently down) and my be sending zip files that are partially corrupted

**Comment by Pacane** [comment]
Someone has sent me the file, I haven't used the file from cypress server myself. Can I upload files in here?

**Comment by rdingwell** [comment]
So the file you have is one that someone sent you and not downloaded from the cypress server, is that correct?  
I'm not sure if you can or cannot attach it here in the issue.  I know you can drag images over but I'm not sure about other file types.

**Comment by Pacane** [comment]
Yes this is right... The company I'm working for registered and downloaded the file. They gave me that file.

**Comment by rdingwell** [comment]
I dont think you'll be able to upload the file here so you'll need to repost this in the pophealth talk list and attach it there.

**Comment by Pacane** [comment]
The best way I've found to upload the file quickly was with dropbox. So here it is. https://dl.dropboxusercontent.com/u/43015964/bundle-latest.zip

**Comment by rdingwell** [comment]
I will not be able to access any files posted on file sharing sites such as drop box.  The best way to get us the file is as I suggested , posting it to the pophealth talk list. https://groups.google.com/forum/#!forum/pophealth-talk

**Comment by rdingwell** [comment]
I'm closing this issue as the zip file in question is not a cypress measure bundle.  It has been altered by having been uncompressed and then repackaged with additional directory structures included in the file hierarchy, making it incompatible with pophealth.  You will need to obtain an actual measure bundle as outlined in the installation instructions.
