### ISSUE TITLE
map_test application not working

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#18]
In its current state, the map_test does not work in any browser I tried, causing JS-errors when trying to calculate the measure (tried in Chrome, Firefox and IE8)

**Comment by pophealth** [comment]
The Map test application will likely be reconstituted in Project Bonnie.  We are still waiting on approval to move forward on Bonnie, but assuming we get approval, Bonnie will be a measure composition tool.  It will allow you to drag and drop components such as demographics, conditions, medications, etc., to build the logic for a measure.  It will also subsume the map_test application as part of its functionality.  Currently it's just a placeholder, but soon Bonnie will be hosted at https://github.com/projectbonnie

**Comment by ssayer** [comment]
The functionality provided by map_test will be included in [Bonnie](https://github.com/pophealth/bonnie). We will not be updating map_test in the meantime
