### ISSUE TITLE
Error in definition of NQF0038

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#21]
I've discovered an error in the measure definition of metric 0038, namely in file NQF_Retooled_Measure_0038_xslx.json:1031

It reads:

```
"standard_code_list": "c1056, c1057",
```

but it should be:

```
"standard_code_list": "N_c1056, N_c1057",
```

With the current definition, only the CVX codes from N_c1057 are inserted, not the CPT's from N_c1056.

**Comment by pophealth** [comment]
This should be fixed in the NQF_Retooled_Measure_0038_xslx.json.patch file since the NQF_Retooled_Measure_0038_xslx.json is generated from the NQF spreadsheet.  The patch file fixes errors that come from the source excel file.

**Comment by kclaes** [comment]
Not quite sure how this .patch file (which seems to fix the textual representation of certain ranges) should fix the problem.

Also, we witnessed this problem because we couldn't figure out why the metric wasn't populated even though the CPT code was present in the patient's procedures. 

After make the change and reloading the measures, it started working.

I stronly believe the patch does not fix the problem described.

-- patches get applied automatically I would assume? If so, the patch doesn't fix the problem described. If not, how must we apply them?
-- we're both talking about [this](https://github.com/pophealth/measures/blob/master/measure_props/NQF_Retooled_Measure_0038.xlsx.json.patch) file, right?

**Comment by kclaes** [comment]
I'll open a new issue for this, as I've discovered quite a few more.
