### ISSUE TITLE
Immunizations with CVX code not picked up

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#22]
I think I have discovered a bug in the way Pophealth handles immunizations that are defined with a CVX code.

In the measure definitions, the CXV codes are part of json blocks of QDS_data_type "procedure_performed", so they are expected to be in the patient's procedures when calculating the measure.

However, both C32 and CCR importers put immunizations in the immunizations collection of a patient, making them accessible only under the immunizations and all_meds properties of the patients.

This mismatch causes immunizations not to work at all if they are only defined by means of CVX codes. 
They only work when defining them as a procedure (with CPT code = verified by us) or as a medication (with RxNorm code = not verified by us).

**Comment by ssayer** [comment]
bug confirmed, fix in progress

**Comment by ssayer** [comment]
Resolved and fix pushed to develop branch QME

**Comment by kclaes** [comment]
confirmed working (NQF0043 as test case)
