### ISSUE TITLE
Installation instructions using "latest" instead of specific versions is just asking for trouble

### ISSUE THREAD

**Issue by vais** [pophealth/popHealth#269]
Please please please update the [installation instructions](https://github.com/pophealth/popHealth/wiki/Installation) to use specific version numbers of popHealth and the measures bundle that are **last known** to work as expected with each other. Pinning installation instructions to "latest" of everything is causing grief to your users.

**Comment by petercyli** [comment]
Was there a specific issue encountered with the latest installation instruction?

**Comment by vais** [comment]
@petercyli Yes, at least for me - please see #268 and see if you can reproduce this. Since downgrading to an older popHealth commit AND an older bundle (2.4.0) is what fixed the issue for me, I can only assume the fault is somewhere in the combination of latest commit and latest bundle.

**Comment by petercyli** [comment]
Will try to reproduce.

I installed popHealth couple weeks ago using the first part of the V.2.1 instruction, and then switched to V.3 instruction after I found out I needed to use the so called “latest” instruction to install V.3.  I didn’t encounter your problem.

Anyway, I should redo it based on V.3 instruction to duplicate your issue.

Thanks.

Peter

**Comment by vais** [comment]
Could the error be specific to a particular CQM? I am not sure how the map/reduce code works, but I believe that's implemented in javascript for each measure? The CQMs I was hitting are: 50, 165, 68, 65, 22, 69, 138, 166, and 155.
