### ISSUE TITLE
Mongo::OperationFailure in PatientsController#show

### ISSUE THREAD

**Issue by SixOThree** [pophealth/popHealth#27]
I receive the following error when clicking on a Patient ID in the Patients list of a measure.

The system is Windows 7 64-bit with 6 gigs of ram. 
Same error on Windows 7 64-bit with 8 gigs of ram.
Same error on Windows Server 2008 R2 with  4 gigs of ram.

The windows installer version 1.4.1 64 bit was used.
# 

Mongo::OperationFailure in PatientsController#show

Database command 'mapreduce' failed: {"assertion"=>"Invalid BSONObj size: 998050363 (0x3B0A7D3B) first element: : null", "assertionCode"=>10334, "errmsg"=>"db assertion failure", "ok"=>0.0}
Rails.root: C:/proj/popHealth/popHealth

Application Trace | Framework Trace | Full Trace
app/controllers/patients_controller.rb:38:in `block in show'
app/controllers/patients_controller.rb:36:in`show'
Request

Parameters:

{"id"=>"502d58de96298613b400014b"}
Show session dump

_csrf_token: "+IsPUgV92aSEfwMKF/SmJcN5tK/9i1WyBnbIOG6vg4c="
session_id: "89d19d77fbb5e2fb8cf8e3cbaeb5fc6a"
warden.user.user.key: ["User", [BSON::ObjectId('502d603b9629860fb8000015')], "$2a$10$DNVVPu.LMykO3LuOrtE0JO"]
Show env dump

GATEWAY_INTERFACE: "CGI/1.1"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8"
HTTP_ACCEPT_CHARSET: "ISO-8859-1,utf-8;q=0.7,*;q=0.3"
HTTP_ACCEPT_ENCODING: "gzip,deflate,sdch"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.8"
REMOTE_ADDR: "127.0.0.1"
REMOTE_HOST: "dhitLaptop8.DHIT.local"
SERVER_NAME: "127.0.0.1"
SERVER_PROTOCOL: "HTTP/1.1"
Response

Headers:
# None

**Comment by ssayer** [comment]
Just to confirm, you downloaded and used http://projectpophealth.org/installer/popHealth-1.4.1-x86_64.exe

This is an error we often see with MongoDB 32 compiled for 32 bit systems.

**Comment by SixOThree** [comment]
Just to be sure I uninstalled and ensured there were no Mongo files left over. Re-installed using the 64 bit version. Looking in Task Manager processes I can verify that mongod.exe does not have *32 next to it. 

I am able to reproduce this error with the fresh install on three machines by registering a new a user, selecting any single measure, clicking on the 'patients' link, then by clicking on any patient id.

**Comment by andrequina** [comment]
popHealth is no longer supported under windows.
