### ISSUE TITLE
Replace LESS with SASS so popHealth can be installed on MS Windows

### ISSUE THREAD

**Issue by vais** [pophealth/popHealth#270]
There is currently nothing stopping one from installing popHealth on MS Windows other than its dependency on LESS for CSS asset compilation. LESS requires `therubyracer` gem which is not supported on MS Windows. Besides this effectively cutting out the most popular OS (for better or worse) in small doctors' offices, requiring to compile the entire V8 virtual machine just to preprocess CSS? Really? When we have SASS written in Ruby? And [Bootstrap ported from LESS to SASS](https://github.com/twbs/bootstrap-sass) linked from the [Bootstrap homepage](http://getbootstrap.com/getting-started/)? Maybe this made sense at some point, but now this is the only thing that makes popHealth not run on Windows, which is kinda ridiculous.

I have a working install of popHealth on my Windows (XP!) virtual machine, and the only "difficult part" was disabling the asset pipeline and pre-compiling all the assets on a Mac, then copying the static assets over to the public directory in the Windows installation. I would be happy to take on the migration from LESS to SASS if I know this would be accepted by the project.

**Comment by carpeliam** [comment]
@vais popHealth migrated from LESS to SASS in #191.

**Comment by vais** [comment]
@carpeliam cool, thanks!
