### ISSUE TITLE
Progress bar in Patients page for a specific measure keeps running

### ISSUE THREAD

**Issue by traduong** [pophealth/popHealth#32]
We use pophealth as part of our CQM reports for our application.
We got the dashboard page up with measures data for patients. When clicking on patients under one specific measure, we got the progress bar spinning and never got any results.
Could anyone give us any tips where should we look in the code or configuration or even mongo data for trouble shooting. Attached is the screenshot.
Thanks for any hints.

![Screen Shot 2013-04-29 at 10 15 29 AM](https://f.cloud.github.com/assets/4294554/440015/0b60c770-b0f4-11e2-8eac-bcb3a5c8df32.png)

**Comment by andrequina** [comment]
It looks like the measure are calculating correctly for you.

The per patient results go into the patient_cache in mongo.  This page should be doing a query against the patient cache.

I'm not sure what version of popHealth you are running, but you probably want to look in the measures controller for the page you are looking at.  In particular, the patients method will be rendering the page you are looking at:

https://github.com/pophealth/popHealth/blob/master/app/controllers/measures_controller.rb

this is the view for the page you are looking at:

https://github.com/pophealth/popHealth/blob/master/app/views/measures/patients.html.erb

Looking at the latest code it looks like that page does an AJAX request back to the measures controller which is handled by the measure_patients method.

That will end up rendering with

https://github.com/pophealth/popHealth/blob/master/app/views/measures/measure_patients.html.erb

My guess is that you are running into a javascript error on the page which is causing the AJAX call to either not fire, or to fail.  Alternatively the AJAX call may be failing on the server side.  If that's the case you should see an exception in your server logs.

**Comment by traduong** [comment]
You are correct. The source we have in the patients.html.erb was
    var sub_id=<%= "'#{params[:sub_id]}'" || 'null' %>;
that causes the java script error due the encoding of single quote
The source you pointed us to is fixed with
    var sub_id= '<%==params[:sub_id] %>';
And we are able to bring up the view now.
Thanks so much.
