### ISSUE TITLE
Issue of always showing all providers as admin user

### ISSUE THREAD

**Issue by traduong** [pophealth/popHealth#34]
Please help to give us any hints to figure out this issue. Please see the attached screen.
Wonder why the pophealth dashboard page for user shows Welcome Master but also shows all providers on Providers list on left panel and practice as GENERAL HOSPITAL on top. It seems it shows everything as admin user.
If you can point us to what to look in database to see any column value tor authentication configuration we should investigate ?
Thanks so much for any response.
![screen shot 2013-05-01 at 12 37 56 pm](https://f.cloud.github.com/assets/4294554/450683/420aef12-b298-11e2-91b3-253b63956241.png)

**Comment by andrequina** [comment]
The practice name is static and can be configured in the file

https://github.com/pophealth/popHealth/blob/master/config/popHealth.yml

PopHealth does not currently handle multiple practices, only multiple
providers.  An admin user can see all providers.  The role permissions are
handled by a plugin called cancan which is configured in the following file.

https://github.com/pophealth/popHealth/blob/master/app/models/ability.rb

Andre

**Comment by andrequina** [comment]
See the following for more info on cancan

https://github.com/ryanb/cancan

**Comment by andrequina** [comment]
Closing issue... Question answered

**Comment by andrequina** [comment]
One more note... If a user does not have admin or staff role set, but does have an NPI for a provider set, that user will only see the information for a single provider
