### ISSUE TITLE
Not showing the measure data for single provider but admin

### ISSUE THREAD

**Issue by traduong** [pophealth/popHealth#37]
I think the data we pushed to PopHealth is correct because we are able to see the measure for the patient when we log in as admin. Please see attachment.

I include the measure 0421 under the provider. Hope you can point us to any other piece of data that we should look into to find the root cause. 
We also wonder if this issue has anything to do with the dates in provider_performances ?

```
"0421" : { "encounter_outpatient_encounter" : [ 
    1364860800, 
    1364774400, 
    1363219200, 
    1367539200 ],
  "bmi_physical_exam_finding" : [ 
    { "date" : 1367452800,
      "value" : 31.32 } ],
  "dietary_consultation_order_communication_provider_to_provider" : [ 
    1367539200 ] },
```

![screen shot 2013-05-05 at 10 33 04 am](https://f.cloud.github.com/assets/4294554/467409/6e4e2646-b678-11e2-995b-6a781517ede9.png)

**Comment by eedrummer** [comment]
The way that the patient and provider are linked are through the NPI. Did the provider you logged in as have an NPI associated with it?

**Comment by eedrummer** [comment]
Closing due to no response. Will reopen if more information is provided.
