### ISSUE TITLE
Delayed Job exception - Unexpected Token ";"

### ISSUE THREAD

**Issue by aaronworsham** [pophealth/popHealth#39]
Error:
Delayed Job is Failing with the following Error;
failed with error 16722: "exception: JavaScript execution failed: SyntaxError: Unexpected token ;"

Steps to reproduce:
I have a brand new install of popHealth on a new Ubuntu server installed following the steps from the 2.1 wiki install page.

After importing the bundle-latest.zip and running the rake db:seed I have a clean db with 56 patient records and 22 measures.

I turn on the delayed job queue with the rake task and log the output to a file.  

I register a new user on popHealth, approve them with the rake task and grant them admin rights.

I login with the user and click on any checkbox on the left, for example 'Home Management Plan of Care (HMPC) Document Given to Patient/Caregiver'

Delayed Job logs a large map reduce section that errors with the exception.

Log is attached at dropbox

https://www.dropbox.com/s/031x8xgq8cbq2zf/delayed_job.log

**Comment by hadleynet** [comment]
Sorry for the delay. This issue is now fixed in the develop branch of popHealth. The issue was version skew between the measures in the 2.2 bundle and the quality-measure-engine gem used by popHealth to calculate the measures.

Marc.

**Comment by pelargir** [comment]
Can this issue be closed?

**Comment by aaronworsham** [comment]
yes, thank you

On Tue, Jul 30, 2013 at 4:52 PM, Matthew Bass notifications@github.comwrote:

> Can this issue be closed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pophealth/popHealth/issues/39#issuecomment-21821944
> .

## 

---

-Aaron Worsham
@saboom // @aaronworsham
248.812.9043
