### ISSUE TITLE
How much time does it take to display data ?

### ISSUE THREAD

**Issue by kirantpatil** [pophealth/popHealth#47]
Hi,

I have installed the popHealth on single Virtual Private server for testing purpose.

I have imported bundle-latest.zip size 13MB.

When I login as admin it says 56 patients loaded but browser is constantly showing progress bar for each data fields it needs to display.

I would like to know how much time does it takes to display the data ?

![screenshot from 2013-08-23 19 45 20](https://f.cloud.github.com/assets/1178055/1016640/9423baf8-0bfe-11e3-987e-483bb75745c5.png)

Thanks.

**Comment by kirantpatil** [comment]
I am using current "develop" branch

**Comment by eedrummer** [comment]
It shouldn't take that long. Do you have the delayed_job worker running in the background? Set up of this is covered in step 9 of the installation: https://github.com/pophealth/popHealth/wiki/Installation-v2.1#9-configure-startup-processes

I'm closing this issue. Questions like this are better addressed on the popHealth mailing list: https://groups.google.com/forum/#!forum/pophealth-talk If we uncover a bug in the troubleshooting process, we can then open a new issue here.

**Comment by kirantpatil** [comment]
Thanks that was the problem.

I installed rvm locally per user and changed the script to use local rvm instance.

Now it works fine.
