### ISSUE TITLE
Can't install on OSX 10.9 easily

### ISSUE THREAD

**Issue by eknelson17** [pophealth/popHealth#72]
A few gems we use are not fully supported on Mavericks, so the install instructions aren't enough to get the project to build.

I made the following changes to my local Gemfile in order to build the project:
- Removed specified version number for libv8 and therubyracer
- Set version number for devise to 3.0.3

I'm not saying this is the solution. It's just what it took to get it running.

**Comment by meadj01** [comment]
Can you give more details on which files to find these version numbers so I can change them on my install?

**Comment by carpeliam** [comment]
@meadj01 the [Gemfile](https://github.com/pophealth/popHealth/blob/master/Gemfile) is located in the root directory of the project, though these gems were updated in 7576c13ebd7a9b8784b63230cd1d0b46e3e83774 so I'm closing this issue.
