### ISSUE TITLE
Font-awesome breaks rake assets:precompile

### ISSUE THREAD

**Issue by rbclark** [pophealth/popHealth#90]
After font-awesome was added, the project no longer compiles properly. When running: 

```
bundle exec rake assets:precompile RAILS_ENV=production
```

It throws the error: 

```
Asset logical path has no extension: font-awesome/Gemfile
```

This is due to vendor/assets/components/font-awesome containing a Gemfile, which is causing the precompile to fail. It seems there isn't any easy way mentioned of working around this. This seems that it may be due to issue sstephenson/sprockets#347. It was mentioned in popHealth/popHealth#66 that a more long term solution is available, and I think that might be a good idea.

**Comment by carpeliam** [comment]
#89 implements the short term fix... maybe the next time this happens, we go for a longer term solution.

**Comment by rbclark** [comment]
Okay sounds good!
